variables:
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  DOCKER_TLS_CERTDIR: "/certs"

  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

image: maven:3.6.3-openjdk-17

stages:
  - compile
  - test
  - build
  - deploy

cache:
  paths:
    - .m2/repository
    - target

build:
  image: ubuntu:latest
  stage: build

  before_script:
    - apt update -y
    - apt install apt-transport-https ca-certificates curl software-properties-common -y
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - 
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    - apt-cache policy docker-ce
    - apt install docker-ce -y
    - export  IMAGE_TAG=`if [ $CI_COMMIT_BRANCH == "staging" ]; then echo $CI_COMMIT_SHORT_SHA; else echo $CI_COMMIT_TAG; fi;`
    - ls
    - docker run --privileged
    - docker load
    - ps -p 1 -o comm=
    - docker login -u "$CI_DOCKER_HUB_USER" -p "$CI_DOCKER_HUB_PASSWORD" $CI_DOCKER_HUB_URL
    - docker info
    - sudo docker ps
  script:
   - sudo docker push gervasioartur/wallet-wise_api-gateway:$IMAGE_TAG
  only:
    - master
    - staging

deploy:
  image: mcr.microsoft.com/azure-cli:latest
  stage: deploy
  before_script:
    - export  IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - az login --username $AZURE_USER --password $AZURE_PASSWORD
  script:
    - az aks install-cli
    - kubectl
    - az aks get-credentials -n wallet-wise-dev-test -g wallet-wise-dev-test --admin
    - sed -i 's/<IMAGE_TAG>/'$IMAGE_TAG'/g' deployment.yml
    - kubectl apply -f deployment.yml
  only:
    - staging
  
  
